<?
// ----------------------------- SCJ
// Страница авторизации пользователя
// ---------------------------------

// Подключение конфига
include "./config.php";

// Проверка на тот случай, если он уже авторизован
if ($_sessionData["auth"] == "yes") {	
	Header("Location: /title.phtml");	
	die;
}

if (!empty($_POST['login'])) {
	// Попытка авторизоваться
	
	if (authUser($_POST["login"], $_POST["password"])) {
		$location = '/title.phtml';
		if (!empty($_SESSION['redirect_url'])) {			
			$location = $_SESSION['redirect_url'];
			unset($_SESSION['redirect_url']);
		}		
		header('Location: '.$location);
		exit();		
	} else {
		$error_message = "Неверная пара логин/пароль";	
	}
}

?>
<head>
<style>
body{background:#f7faff;font-family: Tahoma;}
#content #form{width:515px;margin:150px auto;padding-bottom:30px;}
#content #form #form_inner{background:#edf4ff; border:1px outset #6d9de9;width:398px;margin:0 auto;padding:10px 30px 30px 30px;}
#content #form #form_note{width:390px;margin:0 auto;padding:10px 20px;background:url(/images/form_note_bg.png) top left repeat-x #7db261;border-top:1px solid #a5e78b;border-left:1px solid #a5e78b;border-right:1px solid #a5e78b;font-family:Arial, Helvetica, Verdana, sans-serif;font-size:14px;color:#3d721d;border-top-left-radius:10px;border-top-right-radius:10px;-webkit-border-top-left-radius:10px;-webkit-border-top-right-radius:10px;-moz-border-radius-topleft:10px;-moz-border-radius-topright:10px;}
#content #form #form_note a{text-decoration:none;color:#3d721d;}
#content #form #form_note a:hover{color:#255607;}#content #form #form_note b{color:#356617;}
#content #form #form_inner #account_form{margin:0;padding:0;}
#content #form #form_inner #account_form label, .label{font-size:20px;color:#657788;display:block;margin-bottom:5px;}
#content #form #form_inner #account_form .text_field{width:380px;font-size:20px;border:1px solid #97b5d2;background:url(/images/input_bg.png) top left repeat-x #f7fcff;color:#25313c;}
#content #form #form_inner #account_form .text_field:focus{background-color:#f9f8e4;border:1px solid #bda569;}
.big_button{margin:0px;border:solid 1px #ccc;border-top:solid 1px #ddd;border-left:solid 1px #ddd;font-size:20px;color:#fff;cursor:pointer;line-height:42px;height:42px;padding:0px 15px;overflow:visible;border-radius:5px;-moz-border-radius:5px;-webkit-border-radius:5px;background:	#63839F top repeat-x;border-width:0px;border-right:solid 1px #37516A;border-bottom:solid 1px #37516A;text-shadow:#37516A 1px 1px;}
</style>
<meta http-equiv="Content-type" content="text/html;charset=windows-1251" />
</head>

<body>
<div id="content" align="center">
	<div id="form" align="left">
	    <div id="form_inner">
	    	<div style="position:relative; right:-20px;" align="right" class="label">SPOT2D <? echo DDC_VERSION; ?></div>
	   	<form method="post" id="account_form">
            <label for="email">Логин:</label>
	            <div style="margin-bottom: 20px;"><input name="login" id="email" class="text_field" value="" type="text" style="width:100%"></div>
	            <label for="password">Пароль:</label>
	            <div style="margin-bottom: 30px;"><input name="password" class="text_field" type="password"  style="width:100%"></div>
	            <div style="height: 40px;">
		            <div style="float: left; color: red; padding: 5px;" style="label">
		                <b><?=$error_message; ?></b>
		            </div>
		            <div style="float: right;">
		                <input value="Войти" class="big_button" type="submit">
		            </div>
	            </div>
            </form>
	    </div>
	</div>
</div>
<div>
<img src="/images/<? echo LOGO_IMG; ?>" style="position: absolute; top:10px; left: 20px;">
</div>
</body></html>

